name: Daily Staff Residency Check

on:
  schedule:
    # Runs every day at 6:00 AM UTC (9:00 AM Dubai time)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run email automation
      env:
        EMAIL_HOST: smtp.gmail.com
        EMAIL_PORT: 587
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: node automation-service.js