name: Staff Email Automation

on:
  schedule:
    # يعمل كل 5 دقائق للاختبار
    - cron: '*/5 * * * *'
  workflow_dispatch: # للتشغيل اليدوي

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run email automation
      env:
        EMAIL_HOST: smtp.gmail.com
        EMAIL_PORT: 587
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: node automation-service.js